id: P006786
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20086
  title: རྒྱ་གླིང
  author: ''
  volumes:
    0db4edc9b6e749dcb51ee17e4b61914c:
      image_group_id: I4253
      title: ''
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
